### ISSUE TITLE
把笔记重新整理了一遍

### ISSUE THREAD

**Issue by Hugsy19** [applenob/Cpp_Primer_Practice#34]
地址：https://hugsy.top/Cpp/#/cpp_primer/

在原来的基础上重新整理，做了大量的修改。

想要把这个合入主仓，是不是主仓再建一个分支专门存这个？

**Comment by applenob** [comment]
提交一个pull request即可，不用再建分支

**Comment by uangunai** [comment]
你这个排序有点奇怪，是基于什么规则重新整理的？

**Comment by Hugsy19** [comment]
> 你这个排序有点奇怪，是基于什么规则重新整理的？

还是书上目录的顺序

**Comment by uangunai** [comment]
我咋记得第一章后面是控制流和类的简单使用？顺序对不上耶。

**Comment by Hugsy19** [comment]
> 我咋记得第一章后面是控制流和类的简单使用？顺序对不上耶。

觉等没什么可整理的或后面重复的章节我直接省略掉了
